name: 'dbt_hass'
version: '0.1.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_hass:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  hass_raw_schema: raw
  hass_raw_events_table: hass__events